[platformio]
default_envs = ywd_rf

[env:ywd_rf]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    jgromes/RadioLib@7.7.1
    olikraus/U8g2@2.36.18

build_flags =
    -D YWD_RF_VERSION=\"0.0.1-dev\"
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
